apiVersion: v1
kind: Pod
metadata:
  name: special-app
spec:
  containers:
  - name: special-container
    image: busybox
    command: ["sleep", "3600"]
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "special-workload"
    effect: "NoSchedule"