apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-game
  labels:
    app: MarioGame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MarioGame
  template:
    metadata:
      labels:
        app: MarioGame
    spec:
      containers:
        - name: mario-game
          image: makbanov/supermario:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service-local
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: MarioGame
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80