Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "ubuntu-crio"

  # Give 4GB RAM Memory for VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
  end
end
